import type { Metadata } from "next";
import {
  pbSignatureRegular,
  pbSignatureBold,
  pbSpecialElite,
  roboto,
} from "@/utils/fonts";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { navigation } from "@/lib/dummyData";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${pbSignatureBold.variable} ${pbSignatureRegular.variable} ${pbSpecialElite.variable} animate-fade-in`}
      >
        <div className="grid min-h-[100dvh] grid-rows-[auto_1fr_auto]">
          <Header navigation={navigation} />
          <main role="main">{children}</main>
          <Footer socialHeading="Connect With Us" />
        </div>
      </body>
    </html>
  );
}
